### ISSUE TITLE
Compilation error in dev-c++ 5.11

### ISSUE THREAD

**Issue by Oleg720** [Hopson97/MineCraft-One-Week-Challenge#1]
![screenshot_44](https://user-images.githubusercontent.com/29836552/28790535-f641aa62-7642-11e7-9def-71828ef713ea.png)

**Comment by Hopson97** [comment]
Project requires compiler with support for C++14

If you can, use compiler flag 

-std=c++14

Not sure how this is done in devC++

**Comment by Oleg720** [comment]
What program do you use for compilation?

**Comment by Hopson97** [comment]
code blocks

**Comment by Oleg720** [comment]
Forgive me for troubling you again.
I installed СodeBlocks and connected "-std= c++14", but when compiling, I get an error:
![screenshot_45](https://user-images.githubusercontent.com/29836552/28811269-7beedaf4-76a7-11e7-8c7c-c5c3c6ef2e62.png)

**Comment by Hopson97** [comment]
Did you add the source and headers to the project?

**Comment by Oleg720** [comment]
I just downloaded the project with Github and tried to compile it using the file "project_folder/source/main.cpp"
In CodeBlocks I have added: SFML, GL. glm.

**Comment by Oleg720** [comment]
You can give me your CodeBlocks folder (C:\Program Files (x86))?

**Comment by Hopson97** [comment]
You have to add every file to the project, not just main

**Comment by Oleg720** [comment]
I do not understand (stupid).
Can you compile the project and send it to me?

**Comment by Hopson97** [comment]
I am uploading video now, you will find download link when I make video public
