### ISSUE TITLE
Block Collision

### ISSUE THREAD

**Issue by Glitchcode2447** [Hopson97/MineCraft-One-Week-Challenge#10]
Can you make it so you can walk on and collide with blocks.

**Comment by BearzRobotics** [comment]
I think the better place is [here](https://github.com/Hopson97/HopsonCraft) at his other minecraft project. I fell like this was mostly just a one week challenge and that is it. I could be wrong though

**Comment by Hopson97** [comment]
Glitchcode, you already can walk on blocks

**Comment by Glitchcode2447** [comment]
you can... how?

**Comment by Hopson97** [comment]
You probably downloaded the old version.

https://drive.google.com/file/d/0B-bhEaACRE65WF8ydkROS1hEMTg/view

The newer version was also in the video desc ^
