### ISSUE TITLE
A New World

### ISSUE THREAD

**Issue by IridescentRose** [Hopson97/MineCraft-One-Week-Challenge#102]
# Optimization Update!

An awesome update to make this game faster and bug-free!

# Features:

[ ] - Re-Organized and Standardized Code
[ ] - Better Settings Reader
[ ] - Logger
[ ] - Some Parallel Processing For Chunk Generation
[ ] - Graphics Subsystem Rewrite
[ ] - Looking into memory/file issues
[ ] - New Block System

# Issue Fixing! 

- Fixed #101 
- Fixed #65 
- In Progress #77

**Comment by kennyrkun** [comment]
I think [SFML settings parser](https://github.com/SFML/SFML/wiki/Source:-Settings-Parser) would be great for the settings.

**Comment by IridescentRose** [comment]
Cool, setting up OSX to use OpenMP so I can get work done on the go.

**Comment by kennyrkun** [comment]
Why do you need OpenMP?
