### ISSUE TITLE
Some files missing

### ISSUE THREAD

**Issue by Geeloon** [Hopson97/MineCraft-One-Week-Challenge#103]
Some files included in CMakeList can't not be found anywhere. Like in ./Source/Renderer/, QuadRenderer and CubeRenderer are missing. And in ./Source/Texture  CubeTexture is missing.

**Comment by IridescentRose** [comment]
They aren't missing, just deleted and nobody has updated CMakeLists.txt, but it should still be buildable by `make` assuming that you have a linux-styled terminal environment such as Cygwin or you are using Windows 10 PowerShell's Linux Subsystem.

**Comment by Sollace** [comment]
@NT-Bourgeois-Iridescence-Technologies 
Note: Powershell is not required to use the Linux Subsystem.

I never liked powershill. >.>

**Comment by IridescentRose** [comment]
Oh... the more you know...
