### ISSUE TITLE
Intel G41 GPU proplem

### ISSUE THREAD

**Issue by Saraistupid** [Hopson97/MineCraft-One-Week-Challenge#104]
game not work :D 
http://prntscr.com/jirgpr

**Comment by IridescentRose** [comment]
The Intel G41 chipset has integrated graphics which do not support modern versions of OpenGL, as it has only OpenGL 2.0 support by default. Also, this hardware is very outdated, and I would advise using a newer computer to play this game, as it would not be enjoyable, even if it did work.

**Comment by Saraistupid** [comment]
i dont have money
lol
