### ISSUE TITLE
Nothing Displays To Window

### ISSUE THREAD

**Issue by PyroFlareX** [Hopson97/MineCraft-One-Week-Challenge#109]
Using Manjaro Linux, SFML 2.5.0. The 'esc' key still exits the program, but the window goes, and stays dark, as well as full screen, even with full screen turned off.

**Comment by Hopson97** [comment]
I have reverted the code base to an older version, it could be possible it works now :)

**Comment by Hopson97** [comment]
I have removed something from the code that potentially was causing this issue, so it should hopefully be working now :)

**Comment by PyroFlareX** [comment]
I'll paste the new error, apparently, you forgot to fix stuff with glad.

g++ -std=c++14 -O3 -pipe -ffast-math -fno-inline -mfpmath=sse -flto -fno-omit-frame-pointer -march=native -mtune=native -o Source/GL/GLFunctions.o -c Source/GL/GLFunctions.cpp
In file included from Source/GL/GLFunctions.cpp:1:
Source/GL/GLFunctions.h:4:10: fatal error: glad.h: No such file or directory
 #include <glad.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:18: Source/GL/GLFunctions.o] Error 1

**Comment by Hopson97** [comment]
Thats weird, no idea why those files are split into the GLAD/ and glad/ folders in the repo.

Anyways, I put them into the same folder now, hopefully will work. You just need to tell g++ to find the glad.h file the Source/glad/ directory as additional search paths (

**Comment by PyroFlareX** [comment]
im using the makefile from the old repo, btw you forgot to add it back :P
