### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by guneemwelloeux** [Hopson97/MineCraft-One-Week-Challenge#11]
On Ubuntu 14.04, using the following:
gcc 6.3.0
libglm-dev 0.9.5.1-1

I am getting the following error:
`Source/Camera.cpp: In constructor ‘Camera::Camera(const Config&)’:
Source/Camera.cpp:10:27: error: converting to ‘const glm::detail::tvec3<float, (glm::precision)0u>’ from initializer list would use explicit constructor ‘glm::detail::tvec3<T, P>::tvec3(const A&, const B&, const C&) [with U = int; V = int; W = double; T = float; glm::precision P = (glm::precision)0u]’`
`     position = {0, 0, -3.5};`
`                           ^`

Could you give more details on which versions to use for every library/binary involved?
Thanks

**Comment by rsnyman** [comment]
I just downloaded and compiled (and ran) this on Fedora 26 without a problem. My guess is that your version of GCC is too old. You're running a version of Ubuntu from 3 years ago, you might want to consider upgrading to 16.04.

**Comment by rsnyman** [comment]
I just downloaded and compiled (and ran) this on Fedora 26 without a problem. My guess is that your version of GCC and/or other libraries is too old. You're running a version of Ubuntu from 3 years ago, you might want to consider upgrading to 16.04.

**Comment by OliverBalfour** [comment]
On my Ubuntu 17.04 installation, I just installed SFML, GLEW and GLM (`sudo apt-get install libsfml-dev libglew-dev libglm-dev`) and ran `make` (using GCC 6.3.0), no errors.
