### ISSUE TITLE
how to build in windows cmake

### ISSUE THREAD

**Issue by dongqiceo** [Hopson97/MineCraft-One-Week-Challenge#124]
I cant fix this error,I installed SFML(msys2),but it not find SFML
`CMake Error at cmake_modules/FindSFML.cmake:358 (message):
  Could NOT find SFML (missing: SFML_GRAPHICS_LIBRARY SFML_NETWORK_LIBRARY
  SFML_AUDIO_LIBRARY SFML_WINDOW_LIBRARY SFML_SYSTEM_LIBRARY)
Call Stack (most recent call first):
  CMakeLists.txt:23 (find_package)`

**Comment by Hopson97** [comment]
Not sure what I can do about this myself.

Best I can do help for now is link to this SO post :(

https://stackoverflow.com/questions/39933001/find-sfml-with-cmake-on-windows

**Comment by Hopson97** [comment]
Please let me know if you get it working so i can update the README.md file :)

**Comment by dongqiceo** [comment]
> 不知道我自己能做些什么。
> 
> 我现在可以做的最好的帮助是链接到这个SO帖子:(
> 
> https://stackoverflow.com/questions/39933001/find-sfml-with-cmake-on-windows

thanks,I believe code not problem,so,maybe it is my problem
