### ISSUE TITLE
Wont start - opengl 3.3 requested, gpu only supports 3.1

### ISSUE THREAD

**Issue by x35gaming** [Hopson97/MineCraft-One-Week-Challenge#128]

**Comment by Hopson97** [comment]
Sounds like you need a better gpu

**Comment by qwertychouskie** [comment]
Well, more like a non-lazy Intel.  The Intel HD 3000 iGPU supports GL 3.3 on Linux, but only 3.1 on Windows, and the Windows driver is also buggy (SuperTuxKart had a lot of workarounds specifically for this hardware/driver combo).  Your options are:

- Use Linux.  You'll get GL 3.3.  And it's free.
- Upgrade your processor to a 3rd-gen (I did this in my Dell Inspiron 3520 laptop).  You'll get Intel HD 4000, with support for GL 4, and a pretty significant performance bump.  Usually an 3rd-gen i5 can be had for about $30. https://www.ebay.com/itm/Intel-Core-i5-3380M-CPU-Dual-Core-Processor-2-90-GHz-3MB-Socket-G2-SR0X7/153386147200
- Buy a new computer.  Expensive.

**Comment by x35gaming** [comment]
my laptop has an old amd apu

**Comment by qwertychouskie** [comment]
Hmm...  Check to make sure your driver is the latest from AMD's site, if that doesn't work, "Try Linux" still stands as OpenGL on Linux is generally better than Windows.
