### ISSUE TITLE
Can Build in Xcode, but mouse is jittery and will not move anywhere easily.

### ISSUE THREAD

**Issue by GitHubUsername-rmt** [Hopson97/MineCraft-One-Week-Challenge#131]
Mouse presently useless at normal speed of mouse use. If I go glacially slow with the mouse, it jitters over, over the course of a few seconds, to some new direction. WASD keys work just fine. Screen refreshes just fine while using WASD to move through the world.

Also, where is the file "controls.txt" mentioned when the program starts?

Is my hardware simply too old? Late 2008 Aluminum MacBook, 2 GHz Intel Core 2 Duo, * GB, El Capitan 10.11.6. Java minecraft works and I have a python minecraft that works.

I tried using cmake to build this One Week Challenge, as well, but there were many errors. If there is no solution from the Xcode angle, I'll try to tackle some of the errors.

Thank you!

**Comment by Hopson97** [comment]
Not sure why the issue is happening as I am not a Mac user :( What were the errors when building with CMake?

Regarding Controls.txt, I have no clue where that has gone :thinking:

**Comment by GitHubUsername-rmt** [comment]
Hi Matt,
The first thing I was going to tackle is how to make this compile with C++14. I know how to set the C++14 compilation in Xcode. I do not know how to do that with cmake. I've used make and Makefile, but not cmake. Where do I put that compile flag? As it is this might be compiling with C++98...
If I get stop the C++11 warnings, that might settle some of the errors.
Thanks

**Comment by IridescentRose** [comment]
Hey, it's an issue that was solved before Hopson rolled back the project. If you go to the pre-rollback version, which is linked in the README, you can find the relevant code in the HandleMouse function of the Player.cpp file iirc. There was also a closed issue from a while ago that talked about this.

**Comment by IridescentRose** [comment]
Here's the relevant fix:

```
void Player::mouseInput(const sf::RenderWindow& window)
{

    static bool useMouse = true;
    static ToggleKey useMouseKey (sf::Keyboard::L);

    if (useMouseKey.isKeyPressed()) {
        useMouse = !useMouse;
    }

    if (!useMouse) {
        return;
    }

    static sf::Vector2i center = {
        static_cast<int>(g_renderSettings.resolutionX / 2),
        static_cast<int>(g_renderSettings.resolutionY / 2)
    };

    static auto const BOUND = 89.9999;
    static auto lastMousePosition = sf::Mouse::getPosition(window);
    auto change = sf::Mouse::getPosition(window) - lastMousePosition;

    rotation.y += change.x * 0.05;
    rotation.x += change.y * 0.05;

    if      (rotation.x >  BOUND)
        rotation.x =  BOUND;
    else if (rotation.x < -BOUND)
        rotation.x = -BOUND;

    if      (rotation.y >  360)
        rotation.y = 0;
    else if (rotation.y <  0)
        rotation.y = 360;

    auto windowSize = window.getSize();

    int maxRadius = glm::min(windowSize.x, windowSize.y) / 3;
    glm::vec2 delta = glm::vec2(lastMousePosition.x, lastMousePosition.y) - glm::vec2(center.x, center.y);
    float len = glm::length(delta);
    if (len > maxRadius) {
        sf::Mouse::setPosition(sf::Vector2i((int)center.x, (int)center.y), window);
        lastMousePosition = center;
    } else {
        lastMousePosition = sf::Mouse::getPosition(window);
    }

}
```

**Comment by IridescentRose** [comment]
Instead of g_rendersettings, you need the center of the screen by window resolution.

**Comment by GitHubUsername-rmt** [comment]
WHOA.
Works now. Thank you!
Fast and smooth.

**Comment by IridescentRose** [comment]
Yeah. I remember it because i made that patch.

**Comment by IridescentRose** [comment]
You can close the thread if you are satisfied.

**Comment by GitHubUsername-rmt** [comment]
Sorry I didn't check back. Plowing through a book on C++ game programming...
Thank you!

**Comment by qwertychouskie** [comment]
@GitHubUsername-rmt Kinda off-topic, but if you want experience in C++ games, contributing to a FOSS project like [SuperTux](https://github.com/SuperTux/supertux)/[SuperTuxKart](https://github.com/supertuxkart/stk-code)/[OpenRCT2](https://github.com/OpenRCT2/OpenRCT2)/[Cubosphere](https://github.com/cubosphere/cubosphere-code)/etc. is a great way to get experience.

**Comment by Hopson97** [comment]
If you want, you make a PR for this fix :wink:
