### ISSUE TITLE
SFMLRenderer

### ISSUE THREAD

**Issue by SuperFola** [Hopson97/MineCraft-One-Week-Challenge#137]
I noticed that the SFMLRenderer is commented here and there, thus not used. I guess that's because they are a lot of OpenGL states to reset before being able to draw SFML things (just tried, still haven't found them all).

Posting this issue to know if anyone knows how we could use the SFMLRenderer, since it's disabled at the moment, so far, I added a few glDisables things to make sure things are disabled:
```cpp
void SFMLRenderer::render(sf::RenderWindow& window)
{
    if (m_draws.empty())
        return;

    glDisable(GL_DEPTH_TEST);
    glDisable(GL_CULL_FACE);
    glDisable(GL_BLEND);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
    glBindVertexArray(0);
    glBindTexture(GL_TEXTURE_2D, 0);
    glBindTexture(GL_TEXTURE_CUBE_MAP, 0);
    glUseProgram(0);

    window.pushGLStates();
    window.resetGLStates();

    for (const auto& draw : m_draws)
    {
        window.draw(*draw);
    }

    window.popGLStates();
    m_draws.clear();
}
```

**Comment by DreamHollow** [comment]
SFMLRenderer is leftover code and hopefully my latest pull request will eliminate it.
The entire section had already been commented out, so it's safe to say it wasn't being used in the main program.
Thanks for pointing this out.

**Comment by DreamHollow** [comment]
Calling on @Hopson97 to close this if possible, I think this problem should be fixed now.

**Comment by SuperFola** [comment]
I forgot to close it, thanks for reminding me
