### ISSUE TITLE
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "localhost:0.0"

### ISSUE THREAD

**Issue by NoxFly** [Hopson97/MineCraft-One-Week-Challenge#138]
Hello,
I'm on WSL, I installed gcc, clang, sfml, and vcxsrv.

When I do `./scripts/run.sh`, it runs, I press Enter, then I have:
```
Loading game...
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "localhost:0.0"
      after 33 requests (33 known processed) with 0 events remaining.
```

Any idea for how to fix it ?

**Comment by AptRock327** [comment]
You don't have an X server running.

**Comment by Hopson97** [comment]
https://news.ycombinator.com/item?id=11445356

Never seen this error before, but link might be able to help

**Comment by raphaelthegreat** [comment]
It depends on what WSL version you are running. If you are running WSL 1 then you can follow the instructions in the link that @Hopson97 provided or this tutorial: https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242. If you are running WSL 2 then it is quite a bit harder to achieve GUI support as the linux environment is virualized. You can try this tutorial but I didnt have much success with it: https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242. Keep in mind that WSL does not have GPU hardware acceleration so any OpenGL graphical application will run on software rendering which is very slow. I dont think you will be able to get this working until WSL 2 gets complete GPU support.

**Comment by NoxFly** [comment]
Thanks for your answers,
Indeed, there's no way to run it on WSL 2.
It's also because WSL 2 has indirect display port, which limits the OpenGL's version to 1.4.
SFML is then blocked in this situation.
I've tried on my side to do OpenGL projects that could adapt to WSL, but it's really insane and a waste of time, there's no workaround.

Solutions are to execute it either on Windows and setup all things (dll etc...) or on native Linux. I've done some scripts that are automatically set upping the project depending of your compiler and OS.
