### ISSUE TITLE
glm/GTX/dual_quanternion.hpp  " no such dictionary" 

### ISSUE THREAD

**Issue by RequiemxOP** [Hopson97/MineCraft-One-Week-Challenge#146]

**Comment by DreamHollow** [comment]
There isn't enough information here to diagnose the problem.

Could you please provide your operating system, system version, and if applicable, desktop setup (in the case of Linux something like XFCE, Gnome, or KDE)?

I do recommend re-downloading and rebuilding the source code just in case something was missing in the initial download.
It's extremely rare, but it can happen.
