### ISSUE TITLE
Clouds?

### ISSUE THREAD

**Issue by gotwig** [Hopson97/MineCraft-One-Week-Challenge#23]
I would realy like to know how to make clouds like in minecraft. They are kind of like white blocks, but I think they move(?)

**Comment by IridescentRose** [comment]
Minecraft clouds are created via Perlin Noise (2-dimension) and the highest values of the noise become a cloud. Usually in the formula, these areas of high values are clumped together, thus forming a cloud. Changing the intensity and scale of the noise can create many different effects, so please do experiment with the code. They do move, and can probably be implemented by using a velocity and delta time (cloud += velocity *= deltaTime). They are not truly blocks, but rather just a rendered object which can be generated, and a white transparent color should do (r=1.0, g=1.0, b=1.0, a=0.5). If you implement a weather system, please do make a way to interpolate between the normal color and a darker color (r=0.3, g=0.3, b=0.3, a=0.5). Note that these values are not tested, but tentatively stated.

**Comment by IridescentRose** [comment]
If I can, I might add some code for clouds in this game.

**Comment by gotwig** [comment]
I implemented a very basic method to do clouds, via spawning new chunks in the sky. I am just missing the "moving" part :D I applied the water shader effect to the clouds, but they dont move themself (yet)

**Comment by IridescentRose** [comment]
@gotwig Sounds interesting... but you may not wish to use the water shader exactly... as that's changed, unless you want some waving clouds. I'm working on a system for the Sky Update #37. I'd love to see your code though. And the sky chunks is messing with me right now :P . Good luck :$D

**Comment by UnderTrack** [comment]
@Hopson97 *Same thing, needs to be closed*
