### ISSUE TITLE
MacOS X - Compile issue

### ISSUE THREAD

**Issue by vmarkushin** [Hopson97/MineCraft-One-Week-Challenge#26]
For successful compile, I was need to change `-L/opt/local/bin` to `-L/opt/local/lib` in the `Makefile`.

**Comment by IridescentRose** [comment]
Yeah, that line in the makefile is wrong. I uploaded a patch to fix that. #49

**Comment by UnderTrack** [comment]
@Hopson97 *Same thing, needs to be closed*
