### ISSUE TITLE
Mention Minetest ?

### ISSUE THREAD

**Issue by ThibaultLemaire** [Hopson97/MineCraft-One-Week-Challenge#28]
Hey this is an impressive challenge and a nice proof of feasibility (so I'm definitely not saying to abandon it).

But for the people that may stumble upon it and see it's potential as an alternative to the proprietary Minecraft game, why not at least mention the larger and more mature [Minetest](https://github.com/minetest/minetest) project ?
(I was thinking in the README or something)

**Comment by Hopson97** [comment]
Because they are totally unrelated?

**Comment by Hopson97** [comment]
Sorry I was hostile there :S 

I mean, that would be like walking into an independent fast food shop and seeing McDonald's and Burger King adverts :P

**Comment by ThibaultLemaire** [comment]
I'm sorry, I didn't mean for you to take it the wrong way.
Minetest may be a bigger project, but unlike McDonald's or Burger King, it's community driven. To me, it would more be like walking into a vegetarian shop and seeing a flier for a vegan shop (or vice-versa). They may not agree on everything, and one may have a bigger community, but they do share some common goals.

From the perspective of someone unfamiliar with the code of either projects, they're both open-source C++ Minecraft inspired games. "So how come there's two of them?" and "Which one to choose?"

Provided they have heard of both, a quick search will show Minetest to be more mature, and obviously people will choose it over your project, so I understand your concern.
But you can't simply hold captive your community by not sharing this information, that wouldn't be honest and eventually not work at all.

So see it that way : You walk into a independent fast food, and there's a sign describing *why they're better* than McDonald's and Burger King. McDonald's and Burger King are mentioned, but not adverted for.

Just a few simple words stating how your project differs from Minetest would be enough of a mention. So people have all the keys they need to choose.

**Comment by Hopson97** [comment]
Alright, fair enough.

**Comment by Hopson97** [comment]
Ok, I have made a link in the read me :)
