### ISSUE TITLE
[Ongoing] Graphical & Game Enhancements

### ISSUE THREAD

**Issue by IridescentRose** [Hopson97/MineCraft-One-Week-Challenge#34]
# _Graphical Effects_ #
---

Features left before next pull request:
- YAY

Features So Far:
- [x] FXAA in post-processing
- [x] Move color correction code from ChunkShader to PostProcessShader
- [x] Option to enable or disable all post processing in config
- [x] Rendering to texture & Post-Process Render
- [x] Waving water
- [x] Enable switching code in order to disable an effect if a user changes the value in the config to less than 0 (avoids graphical glitches) or higher than 2 (also strange effects). 
- [x] Ability to change options in the config
- [x] Tri-linear Filter
- [x] Brightness enhancement
- [x] Gamma correction

Upcoming Features:
- Sun/Moon
- Clouds
- Stars
- Day/Night Cycle
- Shadows (basic / advanced)
- Weather & Storms

**Comment by IridescentRose** [comment]
@Hopson97 I've discovered an interesting bug in the Shader class. It seems that the function for setting a uniform float sets the float to an integer value. The function is defined as `void Shader::loadFloat(GLuint location, int value)` instead of `void Shader::loadFloat(GLuint location, float value)`

**Comment by Hopson97** [comment]
Good catch o_O

**Comment by IridescentRose** [comment]
Yeah, water waving was going every second when the float truncated to an integer... I assure you a very smooth experience.

**Comment by Hopson97** [comment]
I was wondering why that was happening! Thanks :P

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
oops.

**Comment by IridescentRose** [comment]
Expecting to be able to finish this tomorrow.

**Comment by IridescentRose** [comment]
Approximately a less than 3% performance hit on my system, so that's great :+1:
