### ISSUE TITLE
[Ongoing] SkyNet... or something like that.

### ISSUE THREAD

**Issue by IridescentRose** [Hopson97/MineCraft-One-Week-Challenge#37]
# Sky Update

Main Planned Features:

Completed Features:
- [x] Clouds (basic)
- [x] Procedural SkyBox
- [x] Ambient Lighting
- [x] Sky Fix (SkyLight class) EDIT: Turns out I'm just dumb -_-
- [x] Sun/Moon Basic
- [x] Tick management system (can be used later for redstone)

Extra Tweaks:
- Cross hair and debug constantly on
- Improved Water Tweaks (which apparently @Hopson97 did about 3 hours after me :stuck_out_tongue_winking_eye: )
- Fixed #40 by modifying contrast and gamma values (texture-based skybox now removed)
- Fixed #39 by removing mip-maps. The resulting pixelation from far away will be fixed in post-processing.
- Fixed #42 by changing all shaders.
- Removed active use of skybox.
- Removed texture-based SkyBox in general.
- Removed Patch-1 to fix #51 
- (was not stated earlier) Implemented Numerical Inventory Access (#9)
- Added smoother flora animations.

Issues to be Closed:
- #40 
- #39 
- #42 
- #51 
- #52 
- #9
- #26 - fixed by Patch-2

Next Update Themes:
# Lighting
# The World
# The Player

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
@Hopson97 Is there any way to edit the vertices of a model without instantly segmentation faulting the program?

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
@Hopson97 Never mind that, I'll just create my own class for the Sun & Moon respectively.
