### ISSUE TITLE
Chunk Generation

### ISSUE THREAD

**Issue by IridescentRose** [Hopson97/MineCraft-One-Week-Challenge#38]
At areas like 0,0 chunk generation randomly stops... The result is a world that can only be in the positive linear coordinate system instead of the negative. Also, chunk generation & loading should be put in a separate thread from the main thread / render thread since it often causes a very unstable framerate & bugs like seen in issue #30. World generation height might also be a concern in the future as the current terrain system causes some hardships with the creation of a sky, as the moon is visible from some hills even when its approximately 9-10 a.m.

**Comment by Hopson97** [comment]
The world generation stopping at 0, 0 is intentional, as the noise + ray cast calculations just don't work well in the negative axis, and seeing this was a one-week challenge, I simply stopped world gen there over finding a way around this

**Comment by IridescentRose** [comment]
Okay, that makes sense. I was wondering why all of a sudden there wasn't a world any more :P I may look in to fixing that later though. For now I think the issue is resolved.
