### ISSUE TITLE
Trees colour changes

### ISSUE THREAD

**Issue by Hopson97** [Hopson97/MineCraft-One-Week-Challenge#39]
The colour of trees appears to change as you move closer/ further from them.

**Comment by IridescentRose** [comment]
The best solution is going to BasicTexture.cpp and changing GL_NEAREST_MIPMAP_NEAREST to GL_NEAREST in order to remove the mipmapping for now. I'll find a shader solution to block out the awkwardness of far away texels instead.

**Comment by IridescentRose** [comment]
@Hopson97 I intended this to be similar to Optifine's "Smart" trees option which makes trees transparent when close and opaque when farther away to improve looks and performance, but by all means if it annoys you, remove it.
