### ISSUE TITLE
Shader filenames are non-standard.

### ISSUE THREAD

**Issue by kiroma** [Hopson97/MineCraft-One-Week-Challenge#42]
Or so do I think, glslangValidator does not support .glsl files.
Changing names from xVertex.glsl/xFragment.glsl to x.vert/x.frag could help bugchecking.

**Comment by IridescentRose** [comment]
That would be great, it also allows for better effects integration in the future with .geom and .comp shaders to make the game more interesting. The problem arises at Shader.cpp line 46 & 47 where `+ ".glsl"` is added to the name of the shader. You could remove this, go to each shader class and add the file extension to each.

**Comment by Hopson97** [comment]
I have now done this
