### ISSUE TITLE
Naming error in CobbleStone file

### ISSUE THREAD

**Issue by Balajanovski** [Hopson97/MineCraft-One-Week-Challenge#46]
I have found a small and easy to fix issue in the `CobbleStone` file located in `/Res/Blocks`.
It seems that despite it being cobblestone, its name is "OakBark".
This should be a very easy issue to fix, simply requiring for you to rename it, yet I am not sure if the renaming of the object in its currently working build would result in some possible propagation of the renaming to create some unforeseen errors. This should be taken into consideration.

CobbleStone file for reference with the arrow and comment added in:
```
Name
OakBark <--- NOTICE HOW ITS CALLED OAKBARK

Id
13

TexAll
3 1

Opaque
1

MeshType
0
```

**Comment by IridescentRose** [comment]
Nothing done in the CobbleStone file will do anything as it does not seem to have the .block extension nor is loaded into the program, as far as I can tell, so this should work fine. Look for the Stone.block file in the same directory, as that it what is being loaded, which appears perfectly fine.

From BlockId.h:
```cpp
enum class BlockId :  Block_t
{
    Air     = 0,
    Grass   = 1,
    Dirt    = 2,
    Stone   = 3,
    OakBark = 4,
    OakLeaf = 5,
    Sand    = 6,
    Water   = 7,
    Cactus  = 8,
    Rose    = 9,
    TallGrass = 10,
    DeadShrub = 11,

    NUM_TYPES
};
```

As you can see, nothing greater than block ID 11 is actually in the game including all the oak planks and cobble stone.

**Comment by Balajanovski** [comment]
So it seems that it is just an unused file? Well in that case the issue can be closed.

**Comment by IridescentRose** [comment]
Yes, it should probably be deleted until we set up an XML parser for the blocks instead.
