### ISSUE TITLE
Compatibility Profile Error on macOS

### ISSUE THREAD

**Issue by AcnodeLabs** [Hopson97/MineCraft-One-Week-Challenge#47]
Loading game...
Warning. Compatibility profile not supported on this platform.
Error. Unable to create the context. Retrying without shared context.
Warning. New context created without shared context.
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 3.3 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 4.1 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = true ; debug = false ; sRGB = false
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Unable to load a shader: ERROR: 0:31: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:32: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:33: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:34: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:35: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:37: Use of undeclared identifier 'rgbNW'
ERROR: 0:38: Use of undeclared identifier 'rgbNE'
ERROR: 0:39: Use of undeclared identifier 'rgbSW'
ERROR: 0:40: Use of undeclared identifier 'rgb
Abort trap: 6

**Comment by IridescentRose** [comment]
Any specifications of your PC or how you built the program? I can try on my mac to see if this happens. It seems only OpenGL 4.1 is enabled which is causing the problems with the shader (#version 330) vs. the expected (#version 410).

**Comment by AcnodeLabs** [comment]
macOS Sierra, NVIDIA GT640, how to select glprofile

**Comment by IridescentRose** [comment]
Change Context.cpp line 17 and add:
`settings.attributeFlags = sf::ContextSettings::Core;`

Recompile the project with `make clean && make`

Tell me if that solves the issues. It will disable the drawing of the debug screen however.
If you wait, the pull request #48 may be accepted.

**Comment by AcnodeLabs** [comment]
Issue Persists

**Comment by IridescentRose** [comment]
Upon research into this issue, you must find a way to compile using a Forward-Compatible OpenGL context... yet SFML has no function yet available for that. Try using -framework OpenGL in your linking command over -lGL assuming you use clang++.

**Comment by orangemi** [comment]
maybe #50 can help.

**Comment by AcnodeLabs** [comment]
Dear 
That has already been tried out coz - lGL was not working , it was compiled using the suggested option, can u send me mac executable to try out , compile can be sorted out later

Sent from my Windows 10 phone

**Comment by IridescentRose** [comment]
Thanks @orangemi I might be able to compile now since I use brew and not ports. I'll see if I can work it out.

**Comment by IridescentRose** [comment]
Good job @orangemi  It works on Mac now! I even managed to get my current fork to work.

![screen shot 2017-10-10 at 18 31 45](https://user-images.githubusercontent.com/12397073/31413878-69ebade0-ade9-11e7-8b8a-45a662c2b1a9.png)

@AcnodeLabs Try re-cloning the newest version of this repository and building, since it seems to work now.
