### ISSUE TITLE
Cheers :)

### ISSUE THREAD

**Issue by Eremiell** [Hopson97/MineCraft-One-Week-Challenge#5]
You basically just fixed the two issues I wanted to report (inconsistent cases & missing Makefile/CMakeLists.txt/whatever), so just cheers I guess. :)  I've built the game yesterday after fixing the issues and planned to report today.

Also good job and go on. The game's lagging quite a bit on my machine, but you have clearly written, isn't not close to optimal atm.

**Comment by Hopson97** [comment]
Cool :)
