### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Hopson97** [Hopson97/MineCraft-One-Week-Challenge#58]
Something seems to be lowering the FPS to a lot less than what it once was 🤔

**Comment by namedtoaster** [comment]
What did you do to solve this? Running it on my VM it runs very slowly

**Comment by kennyrkun** [comment]
@namedtoaster do other games run fine on your VM?

**Comment by namedtoaster** [comment]
@kennyrkun within a limited scope, yes. How can I test the performance of the game?
