### ISSUE TITLE
[Ongoing] It's lit!

### ISSUE THREAD

**Issue by IridescentRose** [Hopson97/MineCraft-One-Week-Challenge#63]
# Lighting Update:

Planned Features:

Completed Features:
- [x] Winter!
- [x] Motion Blur
- [x] Color Boost
- [x] Tonemap
- [x] Implement truly customizable postprocess.
- [x] Antialiasing filter
- [x] Bloom
- [x] Create render filters
- [x] Vignette
- [x] Add a sun color to the lighting...
- [x] Color Correction / Saturation
- [x] Circular sun
- [x] Real frame buffers (as objects)
- [x] Denoise function
- [x] Add LOD bias
- [x] Anisotropic Filtering
- [x] Directional Lighting
- [x] Fog
- [x] Dedicated Post-Processor
- [x] Enhanced Water Waves

Tweaks:
- Mipmaps that don't affect trees (at least that you can tell).
- Global Config Access
- New Shader Options
- Fixed Cloud Movements
- Fixed #66 

Performance impacts:
- 8x FXAA (~6%) 
- Bloom (~12%)
- Motion Blur (~7%)

Next Update:
## The World

**Comment by OperationDarkside** [comment]
Sounds awesome.
(But please be carefull with that motion blur)

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
@OperationDarkside Everyone yells at me about that. It's not even gonna be that noticeable, and if it is... well you could just go to shaders.txt and change the line to `motionblur 0` from `motionblur 1`

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
Also for the last few days, all the big stuff is gonna happen so I won't update the picture to keep the suspense.

**Comment by OperationDarkside** [comment]
@NT-Bourgeois-Iridescence-Technologies I didn't mean to yell. But to know you can disable it in a conf file, makes me happy :-)

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
@OperationDarkside No, it's just that a lot of people criticized me for even thinking about adding it into the game T_T

**Comment by OperationDarkside** [comment]
@NT-Bourgeois-Iridescence-Technologies Don't let yourself be brought down. It's your code. It's about fun. And you're are the only one who knows what entertains you. More features are great. Especially if you can deactivate them at will. I can't do what you are doing. And in the end Hopson decides what goes in here.

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
@OperationDarkside I've just added it and made it super subtle, the only weird artifact is when you fly straight up really fast that sometimes the ground glitches a little.
