### ISSUE TITLE
The game goes completely black occasionally.

### ISSUE THREAD

**Issue by IridescentRose** [Hopson97/MineCraft-One-Week-Challenge#65]
When the player goes above or below certain thresholds and looks straight up or straight down the screen goes black and nothing is rendered...

**Comment by Hopson97** [comment]
I have noticed this too.

Seems to happen on startup and when no chunks are rendered or something.

**Comment by IridescentRose** [comment]
Weirdly it happens at ~50 block intervals like y=54 to y=104 is fine but the rest blacks out. It's also only at certain camera angles...

**Comment by Intekin** [comment]
It seams to be related to the camera location offsets during camera creation in the relation to the frustum.  
Turning off the culling removes the blackness bug.

**Comment by IridescentRose** [comment]
Okay I'll fix it.

**Comment by Hopson97** [comment]
I have reverted the code base to an older version, it could be possible it works now :)
