### ISSUE TITLE
World doesn't render (Visual Studio 2017)

### ISSUE THREAD

**Issue by ghost** [Hopson97/MineCraft-One-Week-Challenge#68]
I have tried using both cmake and manually creating projects trying to get this to work, but each time the world just appears black. I don't think it is an issue with the world as I can move and interact with it based on the info in the corner, but nothing else is drawn.

**Comment by Hopson97** [comment]
https://github.com/Hopson97/MineCraft-One-Week-Challenge/issues/30 ?

**Comment by ghost** [comment]
It seems different, as he could see the sky and the world for a short time, but I never see anything besides the debug menu drawn.

**Comment by IridescentRose** [comment]
What computer specs do you have, and what GPU/drivers?

**Comment by ghost** [comment]
i5-4460, 8GB ram, GTX 1070 and windows 10. All drivers are updated and I have tried rebuilding SFML and it didn't change anything.

**Comment by IridescentRose** [comment]
what fork are you using? Just default?

**Comment by ghost** [comment]
Just default, and I haven't changed any of the code yet.
Edit: Just tried it with another version of SFML, but same result.

**Comment by IridescentRose** [comment]
interesting...

**Comment by ghost** [comment]
I just built it with mingw and the error was still there, so it must be something with my computer, thanks for the help though.

**Comment by IridescentRose** [comment]
Yeah, cuz it works with my mingw...

**Comment by kennyrkun** [comment]
I have the same issue. Built using Visual Studio, SFML 2.4.2.

Nothing but black, except for the text and crosshair. However, I am running on a Radeon R9 270. My issue could be somewhat related to #8, though it does not crash on startup.

**Comment by skypartan** [comment]
The same is happening to me. I'm compiling with SFML 2.5.0 (older versions are crashing on startup). Just the text and crosshair are rendered.
![image](https://user-images.githubusercontent.com/17090482/41016846-5e6ce556-6928-11e8-8e91-2182001359bb.png)

**Comment by peitaosu** [comment]
@skypartan same to me, but I am using SFML 2.4.2. Only text and crosshair are rendered.
OS: Windows 10
Compiler: VS2015
GPU: NVIDIA GTX760

**Comment by Hopson97** [comment]
I have reverted the code base to an older version, it could be possible it works now :)

**Comment by kennyrkun** [comment]
rebuilt from master, the problem persists. however in addition, text and the crosshair no longer display. just pure black.

**Comment by Hopson97** [comment]
You need to press F3 to see the Crosshair/text

Weird the problem persists. :/

**Comment by kennyrkun** [comment]
it runs at about 2 fps, and uses 30% cpu. for some reason, the grounded flag is constantly changing between true and false, and my Y value constantly goes up, all without me touching the keyboard.

**Comment by Hopson97** [comment]
Yeah that's really strange. Wish I knew how I could help you :(

**Comment by Hopson97** [comment]
Ok I think we may have found the issue, probably narrows down to the post processing. We will try fix this and I'll get back to you :)

**Comment by Hopson97** [comment]
Ok, it should be working now hopefully 😄

**Comment by kennyrkun** [comment]
![image](https://user-images.githubusercontent.com/13459291/43740990-7b27d774-9992-11e8-9287-3c5365e8746d.png)

It *almost* works!

I don't really know anything about OpenGL, so I have no idea what would be causing this. Perhaps a faulty renderer?

**Comment by Hopson97** [comment]
Yoo what the heck :D no idea what is going on there lol

**Comment by kennyrkun** [comment]
add a wontfix tag if you're gonna close this issue :b

**Comment by Hopson97** [comment]
Lol

**Comment by EKashpersky** [comment]
@kennyrkun, @skypartan hey folks, I did a fix yesterday, can you check this out? So the issue could be closed, and you could play a bit :p

**Comment by skypartan** [comment]
It works now, Thanks!

**Comment by Hopson97** [comment]
Awesome!
