### ISSUE TITLE
How to build for windows 10

### ISSUE THREAD

**Issue by owen-m1** [Hopson97/MineCraft-One-Week-Challenge#74]

**Comment by IridescentRose** [comment]
Open Code::Blocks, add the repository, get a copy of SFML-2.4.2 from their website. Download GLM and GLEW, extract those to a library. Set the library paths, include paths, and link files in Code::Blocks, then build. Make sure the executable is in the same directory as /res and /shaders and execute.

**Comment by KongfeiH** [comment]
There is my method to build for win 10,open Clion,It is recommended to use MinGW64 to build for win 10, add the repository, get a copy of SFML-2.4.2 from their website（now ,the lastest edition is 2.5,it is compatibale）. Download GLM and GLEW, extract those to a library. add them to the project in  camkefile , then build. Make sure the executable is in the same directory as /res and /shaders and execute.

**Comment by Sollace** [comment]
I thought it was built on windows by default?

Either way, you could always use the Linux Subsystem.

**Comment by KongfeiH** [comment]
But it‘s compatiable with windows and linux，it is easy to build for linux and win by using cmake。by the way，Clion is a cross platform IDE.
