### ISSUE TITLE
Block Texture Issue [Info]

### ISSUE THREAD

**Issue by UnderTrack** [Hopson97/MineCraft-One-Week-Challenge#75]
**Just a warning**, 
Me and Cray were both working on a pass from the previous x16 texture pack to a x64 texture pack, however, Cray had a windows issue and lost the code fixs without uploading merging them.
So take in consideration that the current Branch do have that issue : 

The game will load the texture atlas as it is and will give block textures according to it on a 16x base where the atlas itself have it based on x64. (x16 = 16x16 px and x64 = 64x64 px)

So if textures looks f**k'd up, it's normal.

_I'll try to fix it myself if I enventualy manage to make CMake work, or eventually if he want/can NT will do/compile it for me_

**Comment by IridescentRose** [comment]
I think they all are fine on my fork... 
![screenshot from 2017-10-29 18 33 44](https://user-images.githubusercontent.com/12397073/32694491-14f56580-c70f-11e7-818a-015ee9bcc076.png)

I didn't have to make any adjustments to get it working though.
