### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by OperationDarkside** [Hopson97/MineCraft-One-Week-Challenge#78]
Thanks to @NT-Bourgeois-Iridescence-Technologies the looks are improving constantly and other people contributing improvements, I thought it would be time to think about multiplayer (and I was eager to try it out).

On the weekend I tried to just send the player position via a threaded UDP connection to a C# receiver. In the following gist is the code of both. It took longer than expected, but I didn't know that the whole application crashes if a std::thread goes out of scope.
[https://gist.github.com/OperationDarkside/bd5f157f4d11df11881dfc66a34bd4aa](url)

Following are the communication channels I see a need for at the moment:
- World-Event (digging, placing, weather-change): TCP
- Player-Event (Add Item): TCP
- World-Load (Blocks + Textures + Chunkblocks): TCP
- Player-Load (Position, Inventory): TCP
- Player-Position-Update (Position-Vector + View-Vector): UDP

I chose mostly TCP because those are not yet time-critical, but it's debatable. Some could even be bundled to save memory for threads+connections.

Problems:
- Who should do what? Does the client just do the rendering and the server has all the logic?
- Current code needs to be split. Server has only the data and needs less frameworks, but needs to handle multiple connections and concurrency.

**Comment by Hopson97** [comment]
It'd be incredibly awkward to add multiplayer at this point, seeing as most of the critical stuff was designed for and implemented for a single player game, so adding multiplayer would most likely require a very large rewrite. 

I have been planning to actually remake "HopsonCraft" again, with multiplayer in mind, but for me it is a matter of finding the time, as well as gaining the knowledge for this sort of thing,

**Comment by IridescentRose** [comment]
@Hopson97 @OperationDarkside We're creating a MC one Week Challenge Discord at https://discord.gg/mjSutWm if you want to discuss. Currently its only me, UnderTrack, and Cray. I'll probably be able to push my fork this week since I'm not ridiculously busy.

**Comment by OperationDarkside** [comment]
@Hopson97 You are probably right. So with your permission I would like to create a multiplayer version of your game. Since I don't have much knowledge also in that regard, we could learn from each other. You've mentioned earlier, that you wanted to remake HopsonCraft, but I'm incredibly impatient and want to learn more about game development.^^
If you want, you can pull from my fork, because I remade the blocksystem. Have a strange bug though, if I move the mouse to the side, the picture jumps up a few degrees.

@NT-Bourgeois-Iridescence-Technologies Sounds great. When I find the time I will join you.

**Comment by Hopson97** [comment]
@OperationDarkside If you want to make your own version then I am not going to stop you lol, do whatever you want :P

**Comment by IridescentRose** [comment]
@Hopson97 Can we re-write the entire game? XD

**Comment by Hopson97** [comment]
I would love to do this, but I would create a formal plan first, because as I am inexperienced with programming networking, I don't want to be thrown into a bunch of networking code written by someone else, and have no idea what is going on :P 

Another thing would be implementing some more design patterns. For example, MVC pattern can help keep things modulated, and this can make it easier to collaborate.

**Comment by OperationDarkside** [comment]
Yeah. From this point it gets much more complex and you need to separate the individual blocks of code. I read a few articles about netcode and some even said they didn't put the sending/receiving parts into extra threads and kept it in the main thread. An [article from valve](https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking) talked about having a queue which stores all the events and sends them 30 times a second to the server. There's a lot to do at work at the moment, so I don't have much time, but in the time around christmas I'm definitely going to try some of these things.

**Comment by OperationDarkside** [comment]
@Hopson97 @NT-Bourgeois-Iridescence-Technologies  Hey. Now that I have more time I've been reading into networking. [This](https://gafferongames.com/) guy has some good articles about networking. Have read some of them. A lot about UDP, how to make it more reliable and serialization.

**Comment by IridescentRose** [comment]
Interesting. I'm waiting for my new laptop to be delivered and I can get back to work on this.

**Comment by Hopson97** [comment]
tbh I want to wait until wide-spread support for _full_ C++17 in compilers before doing anything

**Comment by OperationDarkside** [comment]
@Hopson97 What C++17 feature do you need? Afaik the networking ts was moved to C++20. At least if you do it because of networking. I'm currently experimenting with berkley sockets. They are the quasi standard on unix based systems.

**Comment by Hopson97** [comment]
Mainly for the use of the filesystem. 

Right now the only options are boost, which is another dependancy; or platform-specific code, which I am not a huge fan of :P 

SFML has built-in networking capabilities (TCP and UDP) so I thought we could use those, but I am not sure how good they are.

**Comment by kennyrkun** [comment]
Why wait for wide spread adoption of c17? It's already standard, so what does it matter if someone isn't using it? We're using it and if someone else wants to use our project they'll use it too.
