### ISSUE TITLE
Numeric Inventory Access 

### ISSUE THREAD

**Issue by Glitchcode2447** [Hopson97/MineCraft-One-Week-Challenge#9]
Can you make it so i can access the items by pressing numbers 1-5

**Comment by IridescentRose** [comment]
@Glitchcode2447 I'm on it :)

**Comment by IridescentRose** [comment]
@Glitchcode2447 it's implemented in pull request #36 :smiley:

**Comment by UnderTrack** [comment]
@Hopson97 *Solved, needs to be closed*
