### ISSUE TITLE
sf::image i does not work in release mode

### ISSUE THREAD

**Issue by qinyt** [Hopson97/MineCraft-One-Week-Challenge#90]
In release mode of Visual Studio, the sf::image isn't initialized as in debug mode, which results in a break down over image buffer.

**Comment by kennyrkun** [comment]
This seems like an SFML issue, as you already know, since you've posted the same thing on the SFML issue tracker. This is not something we can resolve here, as we do not maintain SFML.

[SFML Issue](https://github.com/SFML/SFML/issues/1328)

**Comment by qinyt** [comment]
@kennyrkun Based on my limited understanding of how C++ works, I mistook the debug version xxx-d-2.dll for release version. Sorry for the trouble or any misleading information it entails whatsoever
