### ISSUE TITLE
GLDraw does work as expected in multi-thread(solved)

### ISSUE THREAD

**Issue by qinyt** [Hopson97/MineCraft-One-Week-Challenge#97]
In the world.cpp's render/load mechanic, everything works fine in a single thread. But when I move the job of loading chunks to another thread, it seems that the texture can not be attached properly.  And yes, I've used the std::mutex lock/unlock correctly. Any help ?
![wechat image_20180123211336](https://user-images.githubusercontent.com/20428486/35277774-cb89ae12-0082-11e8-9fda-fcd4471f7374.png)

**Comment by Hopson97** [comment]
This is probably because opengl has to be used on the thread where the opengl context is created

**Comment by qinyt** [comment]
@Hopson97 But in your source code, you also put the chunk-loading task in another thread. Is there any convention that I don't know about ?
`for (int i = 0; i < 2; i++)
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
        m_chunkLoadThreads.emplace_back([&]()
        {
            loadChunks(camera);
        });`

**Comment by qinyt** [comment]
@Hopson97 Turns out that you are absolutely right, I forgot to initialize the BlockDataBase so as to bind the texture in the main thread. Thanks a lot for the tip!
